In [1]:
import torch
# 引入pytorch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.zeros((2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
## torch.zeros((2, 3))和torch.zeros(2, 3)的区别在于，前者是一个元组，而后者是一个列表。由于torch.zeros()函数可以接受元组和列表作为参数，因此两者的效果是一样的。

In [9]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [10]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [11]:
x = torch.arange(12).reshape((3, 4))
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
x[1, 2] = 9
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

In [13]:
x[0:2, :] = 12
x

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

In [14]:
before = id(a)
before

2261509595840

In [15]:
b = a + b
id(b)

2261509528368

In [16]:
z = torch.zeros_like(b)
print(id(z))
z = a + b
print(id(z))

2261509528208
2261509597200


In [17]:
A = a.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [18]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [19]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms, Alley, Price\n')
    f.write('NA, Pave, 127500\n' )
    f.write('2, NA, 106700\n')
    f.write('4, NA, 178100\n')
    f.write('NA, NA, 140000\n')

In [20]:
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0     NA  106700
2       4.0     NA  178100
3       NaN     NA  140000

In [21]:
print(data)

   NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0     NA  106700
2       4.0     NA  178100
3       NaN     NA  140000


In [22]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[2]
inputs

NumRooms  Alley
0       NaN   Pave
1       2.0     NA
2       4.0     NA
3       NaN     NA

In [23]:
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms  Alley
0       3.0   Pave
1       2.0     NA
2       4.0     NA
3       3.0     NA

In [24]:
# inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley
0       3.0   Pave
1       2.0     NA
2       4.0     NA
3       3.0     NA


In [25]:
x, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
type(inputs.values)

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.