计算梯度

In [2]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [5]:
x.requires_grad_(True)  # 等价于x = torch.arange(4.0, requires_grad=True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [38]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [39]:
y.backward()

In [40]:
x.grad

tensor([ 7., 11., 15., 19.])

In [41]:
x.grad == x * 4

tensor([False, False, False, False])

在默认情况下，Pytorch会累积梯度，我们需要清楚之前的值
每一次反向传播都会累积之前的梯度，因此需要在每次backward之前进行grad.zero_()处理，清楚梯度

In [43]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

深度学习中，我们的目的不是计算微分矩阵，而是计算批量中每个样本，单独计算的偏导数之和

In [46]:
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x, y, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True),
 tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>),
 tensor([0., 2., 4., 6.]))

NameError: name '将某些计算移动到记录的计算图之外' is not defined

将某些计算移动到记录的计算图之外


In [53]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad, u

(tensor([0., 1., 4., 9.]), tensor([0., 1., 4., 9.]))

In [54]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [60]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a, a.grad, d, d / a

(tensor(-0.1960, requires_grad=True),
 tensor(819200.),
 tensor(-160602.9844, grad_fn=<MulBackward0>),
 tensor(819200., grad_fn=<DivBackward0>))

In [69]:
a = torch.arange(16).reshape(4, 4)
a, a * a

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]),
 tensor([[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121],
         [144, 169, 196, 225]]))