In [60]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [61]:
x = torch.arange(4)
len(x)

4

In [62]:
x.shape

torch.Size([4])

In [63]:
A = torch.arange(1, 21).reshape(5, 4)
A

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])

In [64]:
A.T

tensor([[ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19],
        [ 4,  8, 12, 16, 20]])

In [65]:
B = torch.tensor([
    [1, 2, 3],
    [2, 0, 4],
    [3, 4, 5]
])

In [66]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [67]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [68]:
salary = [39750.00, 26500.00, 46500.00, 26500.00, 26500.00, 26500.00, 26500.00, 26500.00, 78719.74, 26500.00]
sum(salary), sum(salary) / 10.5


(350469.74, 33378.07047619048)

In [69]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [70]:
u = torch.tensor([3.0, 4.0])
u, type(u), u.dtype, torch.norm(u)

(tensor([3., 4.]), torch.Tensor, torch.float32, tensor(5.))

In [71]:
x = torch.arange(3, 5)
x, type(x), x.dtype
# torch.norm(x)
# x.astype(torch.float32)
# x = torch.tensor(x, dtype=torch.float32)
x = x.float()
torch.norm(x)

tensor(5.)

In [72]:
x = torch.ones(2, 3, 4)
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [73]:
torch.sum(x, axis=0)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [74]:
torch.sum(x, axis=1)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [75]:
torch.sum(x, axis=2)

tensor([[4., 4., 4.],
        [4., 4., 4.]])

In [76]:
# 设置keepdim=True之后，该dim则会保留，变为1，keep
torch.sum(x, axis=2, keepdim=True)

tensor([[[4.],
         [4.],
         [4.]],

        [[4.],
         [4.],
         [4.]]])

In [77]:
torch.sum(x, axis=[1, 2], keepdim=True)

tensor([[[12.]],

        [[12.]]])

In [78]:
torch.sum(x, axis=[1, 0], keepdim=True).shape

torch.Size([1, 1, 4])