In [4]:
import torch
from torch import nn
import torch.nn.functional as F

In [12]:
class CenterLayer(nn.Module):
    def __init__(self) -> None:
        super().__init__()

    def forward(self, x):
        return (x - x.mean())

layer = CenterLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [20]:
net = nn.Sequential(nn.Linear(8, 128), CenterLayer())

y = net(torch.rand(4, 8))
y.mean()

tensor(0., grad_fn=<MeanBackward0>)

In [21]:
# 带参数的图层
class MyLinear(nn.Module):
    def __init__(self, in_num, out_num) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_num, out_num))
        self.bias = nn.Parameter(torch.randn(out_num))
    
    def forward(self, x):
        linear = torch.matmul(x, self.weight.data) + self.bias.data
        return F.relu(linear)
    
dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[ 0.5054, -0.1121,  0.6060],
        [ 0.5266, -0.8867, -0.2465],
        [ 0.3378,  0.6882, -1.3865],
        [ 1.3743, -0.3981,  0.4481],
        [-0.7836,  1.1534,  0.8977]], requires_grad=True)

In [24]:
dense(torch.rand(1, 5))

tensor([[0., 0., 0.]])

In [25]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))

In [26]:
net(torch.randn(1, 64))

tensor([[12.7604]])