In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
x = torch.arange(4)
torch.save(x, 'x-file')

In [3]:
x_read = torch.load('x-file')
x_read

tensor([0, 1, 2, 3])

In [4]:
# pytorch 存储list
x = torch.arange(4)
y = torch.zeros(4)
torch.save([x, y], 'x-file')
x2, y2 = torch.load('x-file')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [6]:
my_dict = {'x': x, 'y': y}
# torch.save(my_dict, 'mydict')
# my_dict2 = torch.load('mydict')
# my_dict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [8]:
class MLP(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.linear = nn.Linear(10, 256)
        self.output = nn.Linear(256, 10)
    
    def forward(self, x):
        return self.output(F.relu(self.linear(x)))
    
net = MLP()
x = torch.randn(2, 10)
net(x)

tensor([[ 0.4846,  0.3043, -0.3813, -0.0046,  0.1458,  0.2747,  0.2701, -0.3569,
         -0.3228,  0.2444],
        [-0.0337, -0.1003, -0.0291, -0.0692, -0.2094, -0.2306,  0.1521,  0.2360,
          0.0376, -0.0816]], grad_fn=<AddmmBackward0>)

In [9]:
torch.save(net.state_dict(), 'mlp.params')