In [1]:
import torch
from torch import nn
from d2l import torch as d2l

In [3]:
def trans_conv(X, K):
    # X is the input
    # K is the kernel
    h, w = K.shape
    Y = torch.zeros(
        (X.shape[0] + h - 1, X.shape[1] + w - 1)
    )
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            Y[i:i + h, j:j + w] += X[i, j] * K
    return Y

In [7]:
X = torch.tensor([
    [0.0, 1.0],
    [2.0, 3.0]
])
Y = torch.tensor([
    [0.0, 1.0],
    [2.0, 3.0]
])
trans_conv(X, Y), trans_conv(Y, X)

(tensor([[ 0.,  0.,  1.],
         [ 0.,  4.,  6.],
         [ 4., 12.,  9.]]),
 tensor([[ 0.,  0.,  1.],
         [ 0.,  4.,  6.],
         [ 4., 12.,  9.]]))

In [8]:
# Official API
X, K = X.reshape(1, 1, 2, 2), Y.reshape(1, 1, 2, 2)
t_conv = nn.ConvTranspose2d(1, 1, kernel_size=2, bias=False)
t_conv.weight.data = K
t_conv(X)

tensor([[[[ 0.,  0.,  1.],
          [ 0.,  4.,  6.],
          [ 4., 12.,  9.]]]], grad_fn=<ConvolutionBackward0>)