In [4]:
!nvidia-smi

NameError: name 'nvidia' is not defined

In [5]:
import torch
from torch import nn

In [9]:
print(torch.device('cpu'))
print(torch.cuda.device('cuda'))
print(torch.cuda.device('cuda:1'))

cpu


In [10]:
torch.cuda.device_count()

0

In [11]:
def try_gpu(i=0):
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

In [12]:
def try_all_gpus():
    devices = [torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

In [13]:
try_gpu(), try_gpu(4), try_all_gpus()

(device(type='cpu'), device(type='cpu'), [device(type='cpu')])

In [15]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [17]:
x = torch.ones(2, 3, device=try_gpu())
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [20]:
y = torch.rand(2, 3, device=try_gpu(1))
y

tensor([[0.1029, 0.7213, 0.5087],
        [0.9275, 0.4341, 0.5582]])

In [22]:
z = x.cuda(1)
print(x)
print(z)

AssertionError: Torch not compiled with CUDA enabled

In [23]:
y + z

NameError: name 'z' is not defined

In [24]:
z.cuda(1) is z

NameError: name 'z' is not defined

In [26]:
net = nn.Sequential(
    nn.Linear(3, 1)
)
net = net.to(device=try_gpu())

In [27]:
net(x)

tensor([[0.5886],
        [0.6937]], grad_fn=<AddmmBackward0>)

In [28]:
net[0].weight.data.device

device(type='cpu')