In [36]:
import torch
from torch import nn
from d2l import torch as d2l

In [37]:
def pool2d(X, pool_size, mode='max'):
    pool_h, pool_w = pool_size
    Y = torch.zeros(X.shape[0] - pool_h + 1, X.shape[1] - pool_w + 1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i + pool_h, j:j + pool_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i:i + pool_h, j:j + pool_w].sum() / (pool_h * pool_w)
    return Y

In [38]:
X = torch.tensor([
    [0, 1, 2,],
    [3, 4, 5,],
    [6, 7, 8,]
])
pool2d(X, [2, 2])

tensor([[4., 5.],
        [7., 8.]])

In [39]:
pool2d(X, [2, 2], 'avg')

tensor([[2., 3.],
        [5., 6.]])

In [40]:
X = torch.arange(16, dtype=torch.float32).reshape(1, 1, 4, 4)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [50]:
torch_pool2d_max = nn.MaxPool2d(3, stride=1)
torch_pool2d_max(X)

tensor([[[[10., 11.],
          [14., 15.]]]])

In [51]:
torch_pool2d_avg = nn.AvgPool2d(3, stride=1)
torch_pool2d_avg(X)

tensor([[[[ 5.,  6.],
          [ 9., 10.]]]])

In [52]:
X = torch.cat((X, X + 1), 1)
X.shape

torch.Size([1, 2, 4, 4])

In [53]:
pool2d_max = nn.MaxPool2d(3, padding=1, stride=2)
pool2d_max(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])